"""The curated facts for pipeline/regional/nysffla_projects.py.

The New York State Chapter of the Forest Fire Lookout Association (NYS FFLA) writes a monthly newsletter
(2016 to 2026): an "Updates" column with a paragraph per tower, project reports, and history features. The
newsletters are prose, so each fact was read once and written down here in our own words, citing the
newsletter(s) by id (``n<YYYYMM>``, the issue the site files under that month) and, for the work days it
lists, the chapter's projects page (``projects``). nysffla_projects.py checks every cited newsletter's text
(it must name the lookout, and the year unless it is that year's own issue).

Reading notes. The text of two issues is filed under the other's month on the site (the files named June and
July 2017 are the July and June issues), the 2019 March-June files carry 2018 headers, the March 2026 file
repeats April's (so "n202603" is not used), and no issue exists for September 2016, December 2023, December
2024 or October-December 2021. Events whose note says "reported" are dated by the issue that reports them
(the work was recent, the exact year not stated). ``built`` of a tower is here only when the issue says so
explicitly, ``other`` carries observer's-cabin building dates and damage. Towers outside New York (Vermont,
New Jersey, Maine, Massachusetts, Florida) that the newsletters mention are not included.

Conventions as in nwmt_projects_data.py: ``E(year, event, note, *cite)``; one event name per year per lookout.
"""

from __future__ import annotations

from _assoc_east import E, doc

BASE = "https://www.nysffla.org"
PROJECTS = f"{BASE}/projects.html"

# (YYYY-MM, URL) of each monthly newsletter PDF, as the chapter's newsletter pages list them.
NEWSLETTERS = [
    ("2016-01", "https://www.nysffla.org/Newsletters/2016/2016-01.pdf"),
    ("2016-02", "https://www.nysffla.org/Newsletters/2016/2016-02.pdf"),
    ("2016-03", "https://www.nysffla.org/Newsletters/2016/2016-03.pdf"),
    ("2016-04", "https://www.nysffla.org/Newsletters/2016/2016-04.pdf"),
    ("2016-05", "https://www.nysffla.org/Newsletters/2016/2016-05.pdf"),
    ("2016-06", "https://www.nysffla.org/Newsletters/2016/2016-06.pdf"),
    ("2016-07", "https://www.nysffla.org/Newsletters/2016/2016-07.pdf"),
    ("2016-08", "https://www.nysffla.org/Newsletters/2016/2016-08.pdf"),
    ("2016-10", "https://www.nysffla.org/Newsletters/2016/2016-10.pdf"),
    ("2016-11", "https://www.nysffla.org/Newsletters/2016/2016-11.pdf"),
    ("2016-12", "https://www.nysffla.org/Newsletters/2016/2016-12.pdf"),
    ("2017-01", "https://www.nysffla.org/Newsletters/2017/2017-01.pdf"),
    ("2017-02", "https://www.nysffla.org/Newsletters/2017/2017-02.pdf"),
    ("2017-03", "https://www.nysffla.org/Newsletters/2017/2017-03.pdf"),
    ("2017-04", "https://www.nysffla.org/Newsletters/2017/2017-04.pdf"),
    ("2017-05", "https://www.nysffla.org/Newsletters/2017/2017-05.pdf"),
    ("2017-06", "https://www.nysffla.org/Newsletters/2017/2017-06.pdf"),
    ("2017-07", "https://www.nysffla.org/Newsletters/2017/2017-07.pdf"),
    ("2017-08", "https://www.nysffla.org/Newsletters/2017/2017-08.pdf"),
    ("2017-09", "https://www.nysffla.org/Newsletters/2017/2017-09.pdf"),
    ("2017-10", "https://www.nysffla.org/Newsletters/2017/2017-10.pdf"),
    ("2017-11", "https://www.nysffla.org/Newsletters/2017/2017-11.pdf"),
    ("2017-12", "https://www.nysffla.org/Newsletters/2017/2017-12.pdf"),
    ("2018-01", "https://www.nysffla.org/Newsletters/2018-01.pdf"),
    ("2018-02", "https://www.nysffla.org/Newsletters/2018-02.pdf"),
    ("2018-03", "https://www.nysffla.org/Newsletters/2018-03.pdf"),
    ("2018-04", "https://www.nysffla.org/Newsletters/2018-04.pdf"),
    ("2018-05", "https://www.nysffla.org/Newsletters/2018-05.pdf"),
    ("2018-06", "https://www.nysffla.org/Newsletters/2018-06.pdf"),
    ("2018-07", "https://www.nysffla.org/Newsletters/2018-07.pdf"),
    ("2018-08", "https://www.nysffla.org/Newsletters/2018-08.pdf"),
    ("2018-09", "https://www.nysffla.org/Newsletters/2018-09.pdf"),
    ("2018-10", "https://www.nysffla.org/Newsletters/2018-10.pdf"),
    ("2018-11", "https://www.nysffla.org/Newsletters/2018-11.pdf"),
    ("2018-12", "https://www.nysffla.org/Newsletters/2018-12.pdf"),
    ("2019-01", "https://www.nysffla.org/Newsletters/2019-01.pdf"),
    ("2019-02", "https://www.nysffla.org/Newsletters/2019-02.pdf"),
    ("2019-03", "https://www.nysffla.org/Newsletters/2019-03.pdf"),
    ("2019-04", "https://www.nysffla.org/Newsletters/2019-04.pdf"),
    ("2019-05", "https://www.nysffla.org/Newsletters/2019-05.pdf"),
    ("2019-06", "https://www.nysffla.org/Newsletters/2019-06.pdf"),
    ("2019-07", "https://www.nysffla.org/Newsletters/2019-07.pdf"),
    ("2019-08", "https://www.nysffla.org/Newsletters/2019-08.pdf"),
    ("2019-09", "https://www.nysffla.org/Newsletters/2019-09.pdf"),
    ("2019-10", "https://www.nysffla.org/Newsletters/2019-10.pdf"),
    ("2019-11", "https://www.nysffla.org/Newsletters/2019-11.pdf"),
    ("2019-12", "https://www.nysffla.org/Newsletters/2019-12.pdf"),
    ("2020-01", "https://www.nysffla.org/News2020/2020%20Jan%20final.pdf"),
    ("2020-02", "https://www.nysffla.org/News2020/2020%20Feb%20final.pdf"),
    ("2020-03", "https://www.nysffla.org/News2020/2020%20Mar%20final.pdf"),
    ("2020-04", "https://www.nysffla.org/News2020/2020%20Apr%20final.pdf"),
    ("2020-05", "https://www.nysffla.org/News2020/2020%20May%20final.pdf"),
    ("2020-06", "https://www.nysffla.org/News2020/2020%20Jun%20final.pdf"),
    ("2020-07", "https://www.nysffla.org/News2020/2020%20Jul%20final.pdf"),
    ("2020-08", "https://www.nysffla.org/News2020/2020%20Aug%20final.pdf"),
    ("2020-09", "https://www.nysffla.org/News2020/2020%20Sep%20final.pdf"),
    ("2020-10", "https://www.nysffla.org/News2020/2020%20Oct%20final.pdf"),
    ("2020-11", "https://www.nysffla.org/News2020/2020%20Nov%20final.pdf"),
    ("2020-12", "https://www.nysffla.org/News2020/2020%20Dec%20final.pdf"),
    ("2021-01", "https://www.nysffla.org/News2021/2021%20Jan%20final.pdf"),
    ("2021-02", "https://www.nysffla.org/News2021/Feb-2021-final.pdf"),
    ("2021-03", "https://www.nysffla.org/News2021/Mar-2021-final.pdf"),
    ("2021-04", "https://www.nysffla.org/News2021/Apr-2021-final.pdf"),
    ("2021-05", "https://www.nysffla.org/News2021/May-2021-final.pdf"),
    ("2021-06", "https://www.nysffla.org/News2021/Jun-2021-final.pdf"),
    ("2021-07", "https://www.nysffla.org/News2021/Jul-2021-final.pdf"),
    ("2021-08", "https://www.nysffla.org/News2021/Aug-2021-final.pdf"),
    ("2021-09", "https://www.nysffla.org/News2021/Sep-2021-final.pdf"),
    ("2022-01", "https://www.nysffla.org/News2022/2022%20Jan%20final.pdf"),
    ("2022-02", "https://www.nysffla.org/News2022/2022%20Feb%20final.pdf"),
    ("2022-03", "https://www.nysffla.org/News2022/2022%20Mar%20final.pdf"),
    ("2022-04", "https://www.nysffla.org/News2022/2022%20Apr%20final.pdf"),
    ("2022-05", "https://www.nysffla.org/News2022/2022%20May%20final.pdf"),
    ("2022-06", "https://www.nysffla.org/News2022/2022%20Jun%20final.pdf"),
    ("2022-07", "https://www.nysffla.org/News2022/2022%20Jul%20final.pdf"),
    ("2022-08", "https://www.nysffla.org/News2022/2022%20Aug%20final.pdf"),
    ("2022-09", "https://www.nysffla.org/News2022/2022%20Sep%20final.pdf"),
    ("2022-10", "https://www.nysffla.org/News2022/2022%20Oct%20final.pdf"),
    ("2022-11", "https://www.nysffla.org/News2022/2022%20Nov%20final.pdf"),
    ("2022-12", "https://www.nysffla.org/News2022/2022%20Dec%20final.pdf"),
    ("2023-01", "https://www.nysffla.org/News2023/2023%20Jan%20final.pdf"),
    ("2023-02", "https://www.nysffla.org/News2023/2023%20Feb%20final.pdf"),
    ("2023-03", "https://www.nysffla.org/News2023/2023%20Mar%20final.pdf"),
    ("2023-04", "https://www.nysffla.org/News2023/2023%20Apr%20final.pdf"),
    ("2023-05", "https://www.nysffla.org/News2023/2023%20May%20final.pdf"),
    ("2023-06", "https://www.nysffla.org/News2023/2023%20Jun%20final.pdf"),
    ("2023-07", "https://www.nysffla.org/News2023/2023%20Jul%20final.pdf"),
    ("2023-08", "https://www.nysffla.org/News2023/2023%20Aug%20final.pdf"),
    ("2023-09", "https://www.nysffla.org/News2023/2023%20Sep%20final.pdf"),
    ("2023-10", "https://www.nysffla.org/News2023/2023%20Oct%20final.pdf"),
    ("2023-11", "https://www.nysffla.org/News2023/2023%20Nov%20final.pdf"),
    ("2024-01", "https://www.nysffla.org/News2024/2024%20Jan%20final.pdf"),
    ("2024-02", "https://www.nysffla.org/News2024/2024%20Feb%20final.pdf"),
    ("2024-03", "https://www.nysffla.org/News2024/2024%20Mar%20final.pdf"),
    ("2024-04", "https://www.nysffla.org/News2024/2024%20Apr%20final.pdf"),
    ("2024-05", "https://www.nysffla.org/News2024/2024%20May%20final.pdf"),
    ("2024-06", "https://www.nysffla.org/News2024/2024%20Jun%20final.pdf"),
    ("2024-07", "https://www.nysffla.org/News2024/2024%20Jul%20final.pdf"),
    ("2024-08", "https://www.nysffla.org/News2024/2024%20Aug%20final.pdf"),
    ("2024-09", "https://www.nysffla.org/News2024/2024%20Sep%20final.pdf"),
    ("2024-10", "https://www.nysffla.org/News2024/2024%20Oct%20final.pdf"),
    ("2024-11", "https://www.nysffla.org/News2024/2024%20Nov%20final.pdf"),
    ("2025-01", "https://www.nysffla.org/News2025/2025%20Jan%20final.pdf"),
    ("2025-02", "https://www.nysffla.org/News2025/2025%20Feb%20final.pdf"),
    ("2025-03", "https://www.nysffla.org/News2025/2025%20Mar%20final.pdf"),
    ("2025-04", "https://www.nysffla.org/News2025/2025%20Apr%20final.pdf"),
    ("2025-05", "https://www.nysffla.org/News2025/2025%20May%20final.pdf"),
    ("2025-06", "https://www.nysffla.org/News2025/2025%20Jun%20final.pdf"),
    ("2025-07", "https://www.nysffla.org/News2025/2025%20Jul%20final.pdf"),
    ("2025-08", "https://www.nysffla.org/News2025/2025%20Aug%20final.pdf"),
    ("2025-09", "https://www.nysffla.org/News2025/2025%20Sep%20final.pdf"),
    ("2025-10", "https://www.nysffla.org/News2025/2025%20Oct%20final.pdf"),
    ("2025-11", "https://www.nysffla.org/News2025/2025%20Nov%20final.pdf"),
    ("2025-12", "https://www.nysffla.org/News2025/2025%20Dec%20final.pdf"),
    ("2026-01", "https://www.nysffla.org/News2026/2026%20Jan%20final.pdf"),
    ("2026-02", "https://www.nysffla.org/News2026/2026%20Feb%20final.pdf"),
    ("2026-04", "https://www.nysffla.org/News2026/2026%20Apr%20final.pdf"),
    ("2026-05", "https://www.nysffla.org/News2026/2026%20May%20final.pdf"),
    ("2026-06", "https://www.nysffla.org/News2026/2026%20Jun%20final.pdf"),
    ("2026-07", "https://www.nysffla.org/News2026/2026%20Jul%20final.pdf"),
]

MONTHS = ("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")

DOCS: list[dict] = [doc("projects", PROJECTS, "NYS FFLA projects", None, cache="projects.html")]
for _ym, _url in NEWSLETTERS:
    _y, _m = int(_ym[:4]), int(_ym[5:])
    DOCS.append(doc("n" + _ym.replace("-", ""), _url, f"NYS FFLA newsletter, {MONTHS[_m - 1]} {_y}", _y,
                    cache=f"pdf/{_ym}.pdf"))

LOOKOUTS: list[dict] = [
    dict(slug="ampersand-mountain", name="Ampersand Mountain", tower="us-ny-ampersand-mountain", pos="ffla:ny:ampersand-mountain:44.2348:-74.2021",
         find=["Ampersand", "Ampersand Mountain", "Ampersand Mt"],
         events=[
             E(1921, "built", "A 22-foot Aermotor LS-40 tower was erected on Ampersand Mountain, the only NY tower built in 1921.", "n202102"),
             E(1970, "closed", "The Ampersand tower was closed to service in 1970.", "n202102"),
             E(1977, "removed", "The Ampersand tower was removed in 1977.", "n202102"),
         ]),
    dict(slug="azure-mountain", name="Azure Mountain Fire Tower", tower="us-ny-azure-mountain", pos="nhlr:US 520",
         find=["Azure", "Azure Mountain", "Azure Mt"],
         events=[
             E(1918, "built", "The tower was first built in 1918; the Friends celebrated its centennial in 2018.", "n201807"),
             E(1922, "restored", "Existing observer's cabin repaired and put in first-class shape in 1922 as part of the new observer housing standard.", "n202202"),
             E(2017, "restored", "A Student Conservation Association crew recently painted the tower, according to photos on the Friends of Azure Mountain website (reported Aug 2017).", "n201708"),
             E(2018, "modified", "The security fencing on the tower was replaced by Dave Vana and a helper (13 hours of work) as a centennial present, before the July 2018 celebration.", "n201808", "n201805"),
         ]),
    dict(slug="balsam-lake-mountain", name="Balsam Lake Mountain Fire Tower", tower="us-ny-balsam-lake-mountain", pos="nhlr:US 9",
         find=["Balsam Lake", "Balsam Lake Mountain", "Balsam Lake Mt"],
         events=[
             E(1887, "built", "The Balsam Lake Club built a log observatory on the summit in 1887, widely considered New York's first fire tower.", "n201901"),
             E(1901, "destroyed", "The first log observatory was found in ruins in 1901, believed to have been struck by lightning and burned.", "n201901"),
             E(1905, "rebuilt", "A second log observatory was built on the summit in the summer of 1905 by club wardens and neighbors.", "n201901"),
             E(1909, "other", "When the state took over, a small observer's cabin, telephone line and summit road were added in 1909.", "n201901"),
             E(1919, "built", "The first steel tower was erected on the summit in 1919, with materials hauled up by wagon.", "n201901", "n201902", "n201903"),
             E(1999, "restored", "In mid-October 1999 NYSDEC staff and Americorps carried in eight new galvanized cross braces, bolts for the whole tower and windows for its restoration.", "n201903"),
             E(2000, "restored", "Balsam Lake tower reopened June 3, 2000 after restoration under the Catskill Fire Tower Project.", "n202210"),
             E(2016, "restored", "In early May 2016 volunteers stained the observer's cabin and made other repairs while hauling donated lumber to the summit for later landing and step replacement.", "n201606"),
             E(2021, "restored", "Some painting and cleaning was reported done at Balsam Lake Mountain around the May 15, 2021 steward orientation.", "n202106"),
             E(2022, "restored", "NYS Forest Rangers and volunteers replaced badly deteriorated landing boards on Balsam Lake tower in fall 2022.", "n202211"),
             E(2023, "closed", "NYSDEC closed the Balsam Lake observer's cabin museum because it needs repairs.", "n202305"),
             E(2023, "other", "A cab window blew out of Balsam Lake tower over winter 2022-23, found at the spring inspection; one window was given a temporary fix.", "n202305", "n202306", "n202307"),
             E(2023, "restored", "DEC Operations staff installed new operable windows in the Balsam Lake tower cab, replacing badly worn ones (reported autumn 2023).", "n202311"),
             E(2025, "assessed", "An engineer inspected the observer's cabin and the final report reached DEC on Sept. 9; it found the restoration work 'extensive'.", "n202509", "n202511"),
         ]),
    dict(slug="beebe-hill", name="Beebe Hill Fire Tower", tower="us-ny-beebe-hill", pos="nhlr:US 242",
         find=["Beebe", "Beebe Hill"],
         events=[
             E(2022, "closed", "NYSDEC closed Beebe Hill tower after a windstorm blew part of the roof off, pending repairs.", "n202204", "n202205", "n202206"),
             E(2025, "restored", "NYSDEC Region 4 refurbished the tower (roof repairs briefly closed it) and replaced the observer's cabin windows, roof and siding; shown at an October picnic (work year reported).", "n202510", "n202602", "n202604"),
         ]),
    dict(slug="belfry", name="Belfry Fire Tower", tower="us-ny-belfry", pos="nhlr:US 1173",
         find=["Belfry"],
         events=[
             E(2021, "restored", "FFLA volunteers made two trips, with DEC permission, to cover graffiti in the Belfry tower cab (reported).", "n202106"),
         ]),
    dict(slug="berry-hill", name="Berry Hill Tower", tower="us-ny-berry-hill", pos="nhlr:US 54",
         find=["Berry", "Berry Hill"],
         events=[
             E(1934, "built", "CCC crews began building the 60-foot International Derrick tower; the observer's cabin, road and phone line followed that year.", "n202507"),
             E(2020, "closed", "The Berry Hill tower was closed to the public from Oct 19, 2020 while restoration work began on site.", "n202010", "n202011", "n202012"),
             E(2021, "restored", "Antennas were taken off the tower and it was restored for reopening under a DEC-funded project (mostly done by 2 July); graffiti in the cab was cleaned up by September.", "n202107", "n202010", "n202109"),
             E(2026, "restored", "FFLA volunteers stained the observer's cabin in two work days using NYSDEC-supplied stain (reported June 2026).", "n202606"),
         ]),
    dict(slug="black-mountain", name="Black Mountain Fire Tower", tower="us-ny-black-mountain", pos="nhlr:US 1276",
         find=["Black", "Black Mountain", "Black Mt"],
         events=[
             E(1918, "replaced", "A 35-foot steel tower replaced the earlier tower on Black Mountain (Lake George region) in 1918.", "n201802"),
             E(1988, "closed", "The tower was closed in 1988 and remains closed to the public.", "n201802"),
             E(1988, "modified", "A 39-foot antenna was installed above the cab in 1988 to help State Police communications.", "n201802"),
         ]),
    dict(slug="blue-mountain", name="Blue Mountain Fire Tower", tower="us-ny-blue-mountain", pos="nhlr:US 109",
         find=["Blue", "Blue Mountain", "Blue Mt"],
         events=[
             E(1994, "restored", "By 1994 the Blue Mt Fire Tower Restoration Committee and DEC had restored and reopened the tower (new windows, scraping, painting, new wood); the roof blew off soon after and was replaced.", "n201711"),
             E(2017, "modified", "NYSDEC removed the equipment attached to and under the tower in fall 2017 to return it to its historic appearance (reported).", "n201801"),
             E(2019, "restored", "FFLA, NYSDEC and Team Rubicon volunteers worked on the tower on 1-2 June and FFLA volunteers painted it on 8 July, completing the year's major restoration.", "n201906", "n201907", "n202001", "projects"),
             E(2020, "restored", "After graffiti was reported on the tower, cab, cabin foundation and summit rocks, FFLA volunteers went up and cleaned what they could in poor weather (reported).", "n202010"),
             E(2021, "restored", "On May 15, 2021 a crew removed the old siding on the Blue Mountain observer's cabin and installed new; exterior work, incl. replacing floor joists, finished that week.", "n202105", "n202106"),
         ]),
    dict(slug="bramley-mountain", name="Bramley Mountain Fire Tower", tower="us-ny-bramley-mountain", pos="nhlr:US 1808",
         find=["Bramley", "Bramley Mountain", "Bramley Mt"],
         events=[
             E(1950, "built", "The 80-foot steel tower was originally built in 1950, per a Delaware County press release.", "n202505"),
             E(2020, "assessed", "On Aug 25, 2020 the Friends of Bramley Mountain and contractor Davanna LLC inventoried and inspected the dismantled tower's parts, which are stored on a farm.", "n202009", "n202012"),
             E(2024, "rebuilt", "The 80-foot Aermotor tower was re-erected on its original summit by Excelsior Towers, becoming visible above the trees Oct. 17; opened to hikers by early 2025.", "n202411", "n202410", "n202501", "projects"),
         ]),
    dict(slug="buck", name="Buck Fire Tower", tower="us-ny-buck", pos="nhlr:US 1707",
         find=["Buck", "Buck Mountain", "Buck Mt"],
         events=[
             E(1933, "built", "Buck Mountain's 60-foot Aermotor LS 40 tower was erected in 1933 by the Whitney family on their Whitney Park property.", "n202309"),
             E(2022, "restored", "The Town of Long Lake and partners installed all-new stairs, landings and roof by August; FFLA volunteers and town staff then painted the tower.", "n202208", "n202210", "n202209"),
             E(2023, "restored", "Buck Mountain tower opened to the public on Sept 2, 2023 after the Town of Long Lake's restoration and trail project; ribbon cutting Sept 15.", "n202309", "n202310"),
         ]),
    dict(slug="catamount-mountain", name="Catamount Mountain", tower="us-ny-catamount-mountain", pos="ffla:ny:catamount-mountain:44.4258:-74.7570",
         find=["Catamount", "Catamount Mountain", "Catamount Mt"],
         events=[
             E(1911, "built", "A wooden log-framed pyramid tower with no cab was first built on Catamount Mountain in 1911.", "n201905"),
             E(1925, "other", "A new observer's cabin was built at Catamount in 1925.", "n202501"),
         ]),
    dict(slug="cathead-mountain", name="Cathead Mountain", tower="us-ny-cathead-mountain", pos="ffla:ny:cathead-mountain:43.2834:-74.2889",
         find=["Cathead", "Cathead Mountain", "Cathead Mt"],
         events=[
             E(1916, "replaced", "The current steel tower replaced a wooden tower that had been in use since 1910.", "n202007"),
             E(1929, "modified", "The Aermotor LL25 tower was retrofitted with interior stairs in 1929.", "n202007"),
         ]),
    dict(slug="chapin-hill", name="Chapin Hill", tower="us-ny-chapin-hill", pos="ffla:ny:chapin-hill:41.6010:-74.8372",
         find=["Chapin", "Chapin Hill"],
         events=[
             E(1924, "built", "The 60-foot Aermotor LS40 tower was erected in 1924 with Sullivan County funds.", "n202401"),
             E(1941, "destroyed", "A 1941 wildfire destroyed the observer's cabin and burned the first three wooden landings and stairs of the tower.", "n202001"),
         ]),
    dict(slug="cornell-hill-at-wilton-camp-saratoga", name="Cornell Hill Fire Tower", tower="us-ny-cornell-hill-at-wilton-camp-saratoga", pos="nhlr:US 734",
         find=["Cornell", "Cornell Hill"],
         events=[
             E(1923, "built", "Saratoga County approved $1,000 for the tower, observer's cabin and phone line; the tower was finished late in the year and first staffed in 1924 (one issue gives 1924 as its erection year).", "n202301", "n202410", "n202401"),
             E(2008, "relocated", "The tower was taken down in summer and moved to Camp Saratoga in Wilton, where it was restored under Larry Gordon.", "n202301", "n202410"),
         ]),
    dict(slug="crane-mountain", name="Crane Mountain", tower="us-ny-crane-mountain", pos="ffla:ny:crane-mountain:43.5449:-73.9624",
         find=["Crane", "Crane Mountain", "Crane Mt"],
         events=[
             E(2024, "relocated", "The saved Crane Mountain tower cab was moved to Martin's Lumber in time for the Oct. 12 Thurman Fall Farm Tour (reported).", "n202410"),
         ]),
    dict(slug="cross-river-mountain", name="Cross River Mountain Fire Tower", tower="us-ny-cross-river-mountain", pos="nhlr:US 1825",
         find=["Cross River"],
         events=[
             E(1926, "built", "A 60-foot Aermotor LS 40 tower was erected at Ward Pound Ridge Reservation; it no longer stands.", "n201804", "n202305"),
         ]),
    dict(slug="de-bar-mountain", name="De Bar Mountain", tower="us-ny-de-bar-mountain", pos="ffla:ny:de-bar-mountain:44.6035:-74.2205",
         find=["DeBar", "DeBar Mountain", "DeBar Mt", "Debar", "Debar Mountain", "Debar Mt"],
         events=[
             E(1922, "other", "New observer's cabin built in 1922 under the newly adopted standard 12 by 16 foot cabin plan for observers.", "n202202"),
             E(1979, "removed", "The Debar Mountain fire tower was removed in 1979 as a non-conforming structure.", "n202012"),
         ]),
    dict(slug="dickinson-hill", name="Dickinson Hill Fire Tower", tower="us-ny-dickinson-hill", pos="nhlr:US 377",
         find=["Dickinson", "Dickinson Hill"],
         events=[
             E(1924, "built", "The 60-foot Aermotor LS40 tower was erected in 1924 by the Conservation Commission with funds from the City of Troy.", "n202401", "n202411"),
             E(2011, "restored", "Friends of Grafton Lakes State Park restored the tower in 2011.", "n202411"),
             E(2017, "restored", "The tower at Grafton Lakes State Park was newly rehabilitated and freshly painted by fall 2017, when the Journey to the Fire Tower trail opened.", "n201709", "n201710"),
             E(2020, "restored", "FFLA volunteers painted over extensive graffiti on the inside of the Dickinson Hill tower cab, with Park and Friends group permission (reported).", "n202011", "n202012"),
             E(2021, "restored", "Volunteers gave the Dickinson Hill tower a clean coat of paint over graffiti in April 2021.", "n202105", "n202104"),
             E(2022, "restored", "Chapter volunteers painted over significant graffiti in Dickinson Hill tower before the Labor Day holiday weekend.", "n202208"),
             E(2023, "restored", "On April 21, 2023 chapter volunteers painted over graffiti in the Dickinson Hill tower cab.", "n202305"),
             E(2025, "restored", "Park staff and FFLA stewards repainted the tower and replaced its steps and landings over the summer under a Friends of Grafton Lakes grant.", "n202511"),
         ]),
    dict(slug="dix-hill", name="Dix Hill Lookout Site", tower="us-ny-dix-hill", pos="fflos:US 552",
         find=["Dix", "Dix Hill"],
         events=[
             E(1924, "built", "The 60-foot Aermotor LS40 tower was erected in 1924 by the Conservation Commission with funds from a nearby landowner.", "n202401"),
         ]),
    dict(slug="goodnow-mountain", name="Goodnow Mountain Fire Tower", tower="us-ny-goodnow-mountain", pos="nhlr:US 537",
         find=["Goodnow", "Goodnow Mountain", "Goodnow Mt"],
         events=[
             E(2020, "closed", "The cab of the Goodnow tower was locked to the public (stairs open at first, then reported closed through Dec) while SUNY ESF sought funds to repair its roof.", "n202008", "n202010", "n202011"),
             E(2022, "closed", "The cab of Goodnow tower was closed to the public pending repairs, as listed from May 2022.", "n202205", "n202206", "n202207"),
             E(2025, "closed", "Tower, trail and parking area closed from July 7 for about three months while SUNY ESF's contractor repaired the roof and a footing.", "n202507"),
             E(2025, "restored", "SUNY ESF's contractor worked from 7 July to 8 October: steel treads and landings, a new roof, handrails, grating and footing, and a re-roofed and re-sided observer's cabin.", "n202510", "n202507", "n202511"),
         ]),
    dict(slug="gore", name="Gore Fire Tower", tower="us-ny-gore", pos="nhlr:US 1701",
         find=["Gore", "Gore Mountain", "Gore Mt"],
         events=[
             E(1918, "built", "The current 60-foot steel tower was erected in 1918, replacing an earlier wooden tower.", "n201802"),
             E(1919, "destroyed", "A hurricane blew the new steel tower down.", "n201802", "n202001"),
             E(1920, "rebuilt", "The tower blown down in 1919 was rebuilt.", "n201802", "n202001"),
             E(1988, "closed", "The tower was closed in 1988 after years of carrying State Police radio equipment; hikers still visit the site.", "n201802"),
         ]),
    dict(slug="graham-mountain", name="Graham Mountain Fire Tower", tower="us-ny-graham-mountain", pos="nhlr:US 105",
         find=["Graham"],
         events=[
             E(2021, "assessed", "An April 2021 FFLA visit found the Graham tower's footings in good shape and judged that repairs would likely need only lumber replacement.", "n202104"),
         ]),
    dict(slug="hadley-mountain", name="Hadley Mountain Fire Tower", tower="us-ny-hadley-mountain", pos="nhlr:US 110",
         find=["Hadley", "Hadley Mountain", "Hadley Mt"],
         events=[
             E(2000, "restored", "The observer's cabin at the summit received a new roof in 2000.", "n201705"),
             E(2018, "restored", "Volunteers hiked up in early-season snow to repair the cab and observer's cabin after a late-November break-in.", "n201812", "n201905"),
             E(2021, "restored", "Hadley tower volunteers found missing and loose bolts under the stair treads and replaced them (reported July 2021).", "n202107"),
         ]),
    dict(slug="hartzfelt-hill", name="Hartzfelt Hill", tower="us-ny-hartzfelt-hill", pos="ffla:ny:hartzfelt-hill:42.0237:-78.4574",
         find=["Hartzfelt", "Hartzfelt Mountain", "Hartzfelt Mt"],
         events=[
             E(1924, "built", "The 60-foot Aermotor LS40 tower was erected in 1924 with funds from local landowners and towns.", "n202401"),
             E(1973, "removed", "The 60-foot tower was removed in 1973.", "n202401"),
         ]),
    dict(slug="high-point-mountain", name="High Point Mountain", tower="us-ny-high-point-mountain", pos="ffla:ny:high-point-mountain:41.7082:-74.3447",
         find=["High Point"],
         events=[
             E(1912, "built", "The first tower at the Shawangunk Ridge site was erected in 1912 and built from trees.", "n201801"),
             E(1919, "replaced", "A steel tower was placed at the High Point site in 1919, replacing the earlier tree tower.", "n201801"),
             E(1988, "removed", "The steel tower, decommissioned in 1971, was removed in 1988; only footings and old phone poles remain.", "n201801"),
         ]),
    dict(slug="hunter-mountain", name="Hunter Mountain Lookout", tower="us-ny-hunter-mountain", pos="nhlr:US 131",
         find=["Hunter", "Hunter Mountain", "Hunter Mt"],
         events=[
             E(2000, "restored", "Hunter Mountain tower reopened October 17, 2000 after restoration under the Catskill Fire Tower Project.", "n202210"),
             E(2016, "modified", "Volunteer John Slechta installed a new alidade map (made by Liz Cruz) showing local features in the cab over Memorial Day weekend 2016.", "n201606"),
             E(2017, "closed", "From July 10, 2017 DEC closed the tower to the public on weekdays (open weekends) during rehabilitation work; the trails stayed open.", "n201706"),
             E(2017, "restored", "NYSDEC Region 4 rehabilitated the tower before its centennial: new roof and fresh paint, plus new windows per a later issue, funded by a $48,000 Adventure NY grant.", "n201708", "n201706", "n201709"),
             E(2018, "restored", "NYSDEC Region 4 Operations staff built a new front porch on the observer's cabin in summer 2018.", "n201811"),
             E(2025, "restored", "DEC Region 4 installed new windows and siding on the observer's cabin as part of a large cabin preservation effort.", "n202510", "n202509"),
         ]),
    dict(slug="hurricane-mountain", name="Hurricane Mountain Fire Tower", tower="us-ny-hurricane-mountain", pos="nhlr:US 644",
         find=["Hurricane", "Hurricane Mountain", "Hurricane Mt"],
         events=[
             E(1922, "restored", "Existing observer's cabin repaired and put in first-class shape in 1922 as part of the new observer housing standard.", "n202202"),
             E(2015, "restored", "Friends crews restored the tower; it could be climbed again by January 2016 and reopened to hikers after being shut since 1979.", "n201601", "n201605", "n201801"),
             E(2017, "restored", "Friends of Hurricane volunteers painted the whole tower with silver protective paint, paid for by NYSDEC.", "n201801"),
             E(2019, "restored", "A new roof, made by the Friends and flown up with state funding, was installed on July 31 by David Vana's crew just before the centennial.", "n201908", "n201801", "n201901"),
             E(2020, "modified", "Friends of Hurricane Mountain hung panoramic photos in the tower cab in September 2020 after an August attempt failed over mounting hardware.", "n202009", "n202008"),
             E(2021, "modified", "A new map table was carried up and installed in the Hurricane tower cab on Sept 4, 2021, similar to the observer's original.", "n202109", "n202106"),
             E(2024, "modified", "Friends of Hurricane replaced the 2015 safety wire with heavier wire on all four landings after winter ice damage (reported in June 2024).", "n202406"),
         ]),
    dict(slug="ingraham-hill", name="Ingraham Hill", tower="us-ny-ingraham-hill", pos="ffla:ny:ingraham-hill:42.0619:-75.9507",
         find=["Ingraham", "Ingraham Hill"],
         events=[
             E(2016, "destroyed", "An 80-foot tower in Broome County came down (collapsed or was brought down; cause not stated), reported by a member in Nov 2016.", "n201611"),
         ]),
    dict(slug="jackie-jones", name="Jackie Jones Lookout", tower="us-ny-jackie-jones", pos="nhlr:US 213",
         find=["Jackie Jones"],
         events=[
             E(2017, "closed", "The tower was reported closed to the public because of its condition; a restoration and repair project had been approved but had no work date yet (reported April 2017).", "n201704", "n201705"),
             E(2018, "restored", "Team Rubicon, FFLA and park volunteers replaced rotted steps and landings with locust, painted the tower and re-floored the cab over several weekends; finished 3 June.", "n201804", "n201806", "n202106", "projects"),
             E(2021, "assessed", "An April 2021 inspection by the FFLA director found many cab windows missing and heavy graffiti on the Jackie Jones tower.", "n202104"),
             E(2021, "restored", "Volunteers painted over extensive graffiti in the Jackie Jones tower on May 21, 2021; replacing broken windows was planned for the same visit.", "n202106", "n202105"),
         ]),
    dict(slug="kane-mountain", name="Kane Mountain Fire Tower", tower="us-ny-kane-mountain", pos="nhlr:US 111",
         find=["Kane", "Kane Mountain", "Kane Mt"],
         events=[
             E(1925, "built", "Kane Mountain was the only new tower erected in New York in 1925 (centennial celebrated in 2025).", "n202501"),
             E(2019, "restored", "A volunteer painted over graffiti that someone had sprayed on the cab inside and out with yellow paint (reported spring 2019).", "n201906"),
             E(2020, "restored", "FFLA volunteers painted over graffiti on the Kane tower on Sept 15, 2020, after a Covid delay.", "n202009"),
             E(2021, "restored", "Graffiti was painted over in April; in August NYSDEC flew in materials to re-roof the observer's cabin and repair its porch, and the cabin was stained.", "n202105", "n202109", "n202108", "projects"),
             E(2025, "modified", "A donated replica map and an FFLA-funded map table were installed in the cab for the centennial; the map was pulled for moisture damage in autumn, repaired and returned.", "n202508", "n202509", "n202512"),
             E(2025, "restored", "FFLA volunteers gave the observer's cabin a fresh coat of stain ahead of the August centennial.", "n202508"),
         ]),
    dict(slug="kempshall-mountain", name="Kempshall Mountain", tower="us-ny-kempshall-mountain", pos="ffla:ny:kempshall-mountain:44.0245:-74.3298",
         find=["Kempshall", "Kempshall Mountain", "Kempshall Mt"],
         events=[
             E(1925, "other", "A new observer's cabin was built at Kempshall in 1925.", "n202501"),
         ]),
    dict(slug="leonard-hill", name="Leonard Hill Fire Tower", tower="us-ny-leonard-hill", pos="nhlr:US 1205",
         find=["Leonard", "Leonard Hill"],
         events=[
             E(2021, "assessed", "An engineer visited Leonard Hill tower in April 2021 for DEC's structural evaluation; the report had still not arrived in 2022.", "n202205"),
             E(2023, "restored", "NYSDEC staff did minor repairs to Leonard Hill tower: new roof, some stair treads replaced and a cab floor installed; tower stays closed pending an engineer's report.", "n202311"),
         ]),
    dict(slug="loon-lake-mountain", name="Loon Lake Mountain Fire Tower", tower="us-ny-loon-lake-mountain", pos="nhlr:US 1072",
         find=["Loon Lake", "Loon Lake Mountain", "Loon Lake Mt"],
         events=[
             E(1922, "restored", "Existing observer's cabin repaired and put in first-class shape in 1922 as part of the new observer housing standard.", "n202202"),
             E(1928, "destroyed", "The tower fell over onto a lean-to during the winter of 1927-28, per a March 1928 local newspaper report.", "n201909"),
         ]),
    dict(slug="lyon-mountain", name="Lyon Mountain Fire Tower", tower="us-ny-lyon-mountain", pos="nhlr:US 1174",
         find=["Lyon", "Lyon Mountain", "Lyon Mt"],
         events=[
             E(1922, "other", "New observer's cabin built in 1922 under the newly adopted standard 12 by 16 foot cabin plan for observers.", "n202202"),
             E(2020, "restored", "In fall 2020 volunteers carried up and installed new safety wire on the Lyon Mountain tower to replace wire that fell off about two years earlier (reported).", "n202011"),
             E(2023, "restored", "During a July 2023 trail trip, chapter volunteers repaired fencing and did general maintenance at Lyon Mountain tower.", "n202308"),
             E(2024, "modified", "Volunteers installed new safety fencing on the tower on Sept. 22, carrying the fencing and tools up the trail.", "n202409", "projects"),
             E(2024, "restored", "Four FFLA volunteers replaced broken and cracked steps on the tower on Sept. 22.", "n202409", "projects"),
         ]),
    dict(slug="makomis-at-speculator", name="Makomis Fire Tower", tower="us-ny-makomis-at-speculator", pos="nhlr:US 1779",
         find=["Makomis"],
         events=[
             E(2019, "restored", "Owner Mike Vigeli finished restoring the dismantled tower (with Pat's Welding) and was seeking a site to erect it (reported 2019).", "n201911", "n201909"),
             E(2022, "relocated", "Historic Makomis tower, kept in storage near Plattsburgh, was re-erected in the Village of Speculator by Excelsior Towers with chapter volunteers around July 4 weekend.", "n202207", "n202208", "n202210", "projects"),
         ]),
    dict(slug="makomis-fire-tower-original", name="Makomis Fire Tower (original site)", tower="us-ny-makomis-fire-tower-original", pos="fflos:US 2102",
         find=["Makomis"],
         events=[
             E(1911, "built", "A wooden, fully enclosed tower was built on private club land in North Hudson in 1911.", "n201909"),
             E(1912, "built", "The Makomis tower was among the first eleven steel fire towers erected in the Adirondacks, in 1912.", "n202101"),
             E(1916, "replaced", "The wooden tower was replaced in 1916 by a 40-foot steel Aermotor LL25, one of the first ten steel towers in NYS.", "n201909"),
             E(1970, "closed", "The tower was closed in 1970 after serving fire spotting; it was later dismantled and sold on.", "n201909"),
         ]),
    dict(slug="mccarty-hill", name="McCarty Hill", tower="us-ny-mccarty-hill", pos="ffla:ny:mccarty-hill:42.2564:-78.6950",
         find=["McCarty", "McCarty Hill"],
         events=[
             E(1940, "built", "The Conservation Department and CCC Camp 106 (Camp Seneca) men erected the 82.5-foot McCarty Hill tower in 1940.", "n202204"),
         ]),
    dict(slug="moosehead-mountain-at-industry-city", name="Moosehead Mountain Lookout (now at Industry City)", tower="us-ny-moosehead-mountain-at-industry-city", pos="ffla:ny:industry-city-relocated-moosehead:40.6576:-74.0075",
         find=["Moosehead"],
         events=[
             E(2016, "relocated", "Davana LLC finished refurbishing the former Moosehead Mountain tower and re-erecting it in a courtyard at Industry City in Brooklyn (reported Nov 2016).", "n201611"),
         ]),
    dict(slug="morgan-hill", name="Morgan Hill", tower="us-ny-morgan-hill", pos="ffla:ny:morgan-hill:42.7678:-75.9976",
         find=["Morgan", "Morgan Hill"],
         events=[
             E(1941, "built", "The tower on Morgan Hill was erected in 1941, completing the Susquehanna Hills tower system.", "n202507"),
             E(2025, "relocated", "Doug Randall moved the former Morgan Hill observer's cabin from the Labrador Unique Area to the base of his private tower, with DEC help, for a future museum.", "n202511"),
         ]),
    dict(slug="mount-adams", name="Mount Adams Fire Tower", tower="us-ny-mount-adams", pos="nhlr:US 549",
         find=["Adams", "Mount Adams", "Mt Adams", "Mt. Adams"],
         events=[
             E(1922, "other", "New observer's cabin built in 1922 under the newly adopted standard 12 by 16 foot cabin plan for observers.", "n202202"),
             E(2004, "restored", "An initial restoration of the tower took place in 2004.", "n201707"),
             E(2008, "other", "Wind blew the roof off the tower in 2008.", "n201707"),
             E(2011, "restored", "A new wind-resistant roof, built off site, was helicoptered in with DEC support and installed in summer 2011 under the ADK High Peaks Foundation project; footing repairs followed.", "n201707"),
             E(2013, "restored", "The ADK High Peaks Foundation's restoration of the tower (roof, footings, windows, maps, paint) was completed in 2013.", "n201707"),
             E(2017, "closed", "DEC advised the public to avoid the tower after ice and wind damaged its top landing, pending repairs planned for later in 2017 (reported March 2017).", "n201703"),
             E(2017, "restored", "A volunteer from the Mount Adams crew replaced and repaired the tower's safety netting on May 13, 2017.", "n201707"),
             E(2024, "modified", "ADK High Peaks Foundation and nine volunteers mounted a new graffiti-resistant interpretive history sign on the tower's first landing on May 11.", "n202405", "n202404"),
         ]),
    dict(slug="mount-arab", name="Mount Arab Fire Tower", tower="us-ny-mount-arab", pos="nhlr:US 108",
         find=["Mount Arab", "Mt Arab", "Mt. Arab"],
         events=[
             E(1918, "built", "A 35-foot Aermotor LS 40 tower was placed on the summit in 1918.", "n201807", "n201802"),
             E(1923, "other", "A new observer's cabin was built in 1923.", "n202301"),
             E(2018, "restored", "Volunteers carried new flooring materials to the observer's cabin in September 2018; photos of the new cabin floor were reported in February 2019.", "n201809"),
             E(2020, "restored", "The Student Conservation Association's Adirondack Corps painted and restored the tower, and volunteers fitted new cab windows between September and 4 October.", "n202009", "n202010", "n202003"),
             E(2024, "modified", "Friends of Mt. Arab refurnished the observer's cabin with period pieces so it looks as if the observer just stepped out (reported).", "n202406"),
         ]),
    dict(slug="mount-beacon", name="Mount Beacon Fire Tower", tower="us-ny-mount-beacon", pos="nhlr:US 655",
         find=["Beacon", "Mount Beacon"],
         events=[
             E(2018, "restored", "Volunteers worked on the tower on July 14, removing chicken wire and graffiti.", "n201808"),
             E(2021, "assessed", "An April 2021 FFLA visit found heavy graffiti on the Mount Beacon tower and recommended examining its footings.", "n202104"),
             E(2021, "restored", "Graffiti was removed from the tower and cab, the footings repaired (with concrete work) and the flagpole rope replaced.", "n202106", "n202107", "n202109"),
         ]),
    dict(slug="mount-morris", name="Mount Morris Fire Watchtower, Harlem", tower="us-ny-mount-morris", pos="ffla:ny:morris-mount:44.1598:-74.4752",
         find=["Marcus Garvey", "Mount Morris"],
         events=[
             E(2019, "restored", "The historic fire watchtower in Marcus Garvey Park, Harlem, reopened after a completed restoration project (reported Oct 2019); not open for climbing.", "n201911"),
         ]),
    dict(slug="mount-nimham", name="Mount Nimham Fire Tower", tower="us-ny-mount-nimham", pos="nhlr:US 314",
         find=["Nimham", "Ninham"],
         events=[
             E(1940, "built", "CCC Camp P-135 of Peekskill erected the 82.5-foot International Derrick tower on Nimham Mountain in 1940.", "n202201"),
             E(1994, "destroyed", "The Nimham observer's cabin was burned in 1994, years after the tower stopped operating.", "n202201"),
             E(2005, "restored", "Volunteers organized by the Town of Kent finished restoring the tower (without a roof); it was rededicated and reopened on July 24, 2005.", "n202201"),
             E(2017, "restored", "The Kent Conservation Foundation replaced all the wood on the 82-foot-6-inch tower in 2017 (reported).", "n201807"),
         ]),
    dict(slug="nelson-mountain", name="Nelson Mountain", tower="us-ny-nelson-mountain", pos="ffla:ny:nelson-mountain:41.2477:-73.8606",
         find=["Nelson"],
         events=[
             E(2023, "removed", "A hiker found on Jan 29, 2023 that the collapsed remains of the Nelson tower on Salt Hill, and site containers, had been removed.", "n202302"),
         ]),
    dict(slug="new-boston-at-thompson-park-zoo", name="New Boston Lookout (now at the Thompson Park Zoo)", tower="us-ny-new-boston-at-thompson-park-zoo", pos="ffla:ny:thompson-park-zoo-relocated-new-boston:43.9626:-75.8829",
         find=["Thompson Park", "Thompson Park Zoo"],
         events=[
             E(2016, "restored", "The former New Boston tower, now at the Thompson Park zoo, was repaired in spring with a $500 FFLA restoration grant.", "n201604", "n202505"),
         ]),
    dict(slug="number-four-at-lowville-demonstration-forest", name="Number Four Fire Tower (now at Lowville Demonstration Forest)", tower="us-ny-number-four-at-lowville-demonstration-forest", pos="ffla:ny:lowville-demonstration-forest-relocated-number-four:43.8093:-75.4731",
         find=["Number 4", "Number Four"],
         events=[
             E(1928, "built", "Fisher Forestry erected the Number Four lookout, an Aermotor LX-25 with ladder-style stairs, by 1928.", "n202306"),
             E(1945, "modified", "An observer's cabin and standard stairs were added to Number Four tower in 1945, replacing the original ladder-style stairs.", "n202306"),
         ]),
    dict(slug="number-seven-hill", name="Number Seven Hill", tower="us-ny-number-seven-hill", pos="ffla:ny:number-seven-hill:42.6072:-73.4487",
         find=["Number 7", "Number 7 Hill"],
         events=[
             E(1923, "other", "A new observer's cabin was built at Number 7 Hill in 1923.", "n202301"),
         ]),
    dict(slug="orangeburg-at-ferncliff-forest", name="Ferncliff Forest Fire Tower", tower="us-ny-orangeburg-at-ferncliff-forest", pos="nhlr:US 1117",
         find=["Ferncliff"],
         events=[
             E(2019, "restored", "Graffiti was painted out on 22 April and again on 1 July after new marks appeared, including on the footings.", "n201905", "n201906", "n201907"),
             E(2021, "restored", "Volunteers gave the Ferncliff tower a clean coat of paint over graffiti in April 2021.", "n202105"),
             E(2023, "restored", "The chapter painted over graffiti on Ferncliff Forest tower in April 2023 after vandals had marked the cab, roof, footings and steel.", "n202305"),
         ]),
    dict(slug="overlook-mountain", name="Overlook Mountain Fire Tower", tower="us-ny-overlook-mountain", pos="nhlr:US 223",
         find=["Overlook"],
         events=[
             E(1999, "restored", "Overlook tower reopened June 5, 1999 after restoration under the Catskill Fire Tower Project, the first of five Catskill towers.", "n202210"),
         ]),
    dict(slug="owls-head", name="Owls Head Fire Tower", tower="us-ny-owls-head", pos="nhlr:US 670",
         find=["Owls Head"],
         events=[
             E(2023, "restored", "A volunteer carried paint up and covered graffiti on Owls Head tower in July 2023 after early-July storms.", "n202308"),
         ]),
    dict(slug="padlock-hill-at-state-fair", name="Padlock Hill Lookout (now at the State Fair)", tower="us-ny-padlock-hill-at-state-fair", pos="ffla:ny:state-fair-relocated-padlock-hill:43.0705:-76.2185",
         find=["Padlock", "Padlock Hill"],
         events=[
             E(1940, "built", "The Civilian Conservation Corps erected the tower at Padlock Hill in 1940 (it later moved to the state fairgrounds).", "n202507", "n202403"),
         ]),
    dict(slug="pillsbury-mountain", name="Pillsbury Mountain Fire Tower", tower="us-ny-pillsbury-mountain", pos="nhlr:US 645",
         find=["Pillsbury", "Pillsbury Mountain", "Pillsbury Mt"],
         events=[
             E(1924, "replaced", "The Champlain Realty Company replaced an earlier wooden tower with the 60-foot Aermotor LS-40 steel tower that still stands.", "n202403"),
             E(2019, "restored", "FFLA volunteers replaced steps and two landings and painted most of the tower in September, with materials flown in by DEC; major work continued into 2020.", "n201910", "n202001", "projects"),
             E(2020, "restored", "Volunteers finished two landings and three flights of steps by 30 August, then all remaining stair treads and one more landing by early October; three landings were left.", "n202009", "n202010", "projects"),
             E(2021, "restored", "On July 24, 2021 volunteers completed the last landings on the Pillsbury tower, finishing the stair and landing restoration.", "n202108", "n202107"),
             E(2023, "modified", "A five-person crew put up new safety fencing along the stairs and landings of Pillsbury tower on Sept 16, 2023; the cab remains closed.", "n202310"),
             E(2024, "modified", "Chapter volunteers' safety fencing on the tower was nearly finished; final stapling was scheduled for a work day in mid-July 2024.", "n202404", "n202405", "n202406"),
             E(2024, "other", "A wall of the observer's cabin collapsed and debris fell onto the tower trail; DEC was to clear it (notice of Sept. 20).", "n202409"),
             E(2025, "removed", "NYS DEC burned the collapsed observer's cabin on the summit in mid-April; DEC listed it as removed and flew out the cabin-fire debris in Nov. 2025.", "n202505", "n202506", "n202512"),
         ]),
    dict(slug="poke-o-moonshine", name="Poke-O-Moonshine Fire Tower", tower="us-ny-poke-o-moonshine", pos="nhlr:US 265",
         find=["Poke O", "Poke O Moonshine", "Poke-O", "Poke-O-Moonshine"],
         events=[
             E(1922, "other", "New observer's cabin built in 1922 under the newly adopted standard 12 by 16 foot cabin plan for observers.", "n202202"),
             E(2003, "restored", "A NYSDEC archive photo shows the tower being painted in 2003 during the Friends-led restoration.", "n201701"),
             E(2005, "restored", "Per a 2017 grant application, the Friends of Poke-O-Moonshine and DEC restored the tower as an educational and historic site in 2005.", "n201712"),
         ]),
    dict(slug="red-hill", name="Red Hill Fire Tower", tower="us-ny-red-hill", pos="nhlr:US 106",
         find=["Red", "Red Hill"],
         events=[
             E(2000, "restored", "Red Hill tower reopened July 15, 2000 after restoration under the Catskill Fire Tower Project.", "n202210"),
         ]),
    dict(slug="rock-rift", name="Rock Rift Fire Tower", tower="us-ny-rock-rift", pos="nhlr:US 1183",
         find=["Rock Rift"],
         events=[
             E(2018, "closed", "Rock Rift tower was listed as closed to the public in the September 2018 newsletter (reason not given).", "n201809"),
             E(2020, "closed", "The Rock Rift tower was reported as closed to the public while the Town of Tompkins sought an engineering inspection to make it safe (reported).", "n202011", "n202010"),
             E(2021, "assessed", "The Town of Tompkins had engineer Jim Forbes inspect the Rock Rift tower; his report gave firm repair cost figures (reported spring 2021).", "n202105", "n202010", "n202101"),
             E(2025, "restored", "Volunteers with the Town of Tompkins started restoration in August and had replaced all steps and landings by month's end; remaining work was set for 2026.", "n202509", "n202508", "n202510", "projects"),
         ]),
    dict(slug="rondaxe-bald-mountain", name="Rondaxe (Bald) Mountain Fire Tower", tower="us-ny-rondaxe-bald-mountain", pos="nhlr:US 112",
         find=["Bald", "Bald Mountain", "Bald Mt"],
         events=[
             E(2004, "restored", "Friends of Bald Mountain and NYSDEC (work began after 2002) scraped and painted the tower, replaced steps, cab floor, safety wire and windows, and repaired footings; reopened by 2004.", "n201702"),
             E(2005, "restored", "Bald (Rondaxe) Mountain tower reopened to hikers in 2005 after restoration by the Friends of Bald Mountain (as quoted from a magazine article).", "n202302"),
             E(2023, "modified", "Fred Knauf replaced the Bald Mountain cab's observer map table with a new UV-protected map, aligned on three peaks and screwed down (reported Sept 2023).", "n202309"),
         ]),
    dict(slug="roosa-gap", name="Roosa Gap Firetower", tower="us-ny-roosa-gap", pos="ffla:ny:roosa-gap:41.6176:-74.4267",
         find=["Roosa Gap"],
         events=[
             E(1948, "built", "The 35-foot Aermotor tower and an observer's cabin were erected on private land; the tower began operating that year.", "n202604"),
         ]),
    dict(slug="salamanca", name="Salamanca", tower="us-ny-salamanca", pos="ffla:ny:salamanca:42.1996:-78.7127",
         find=["Salamanca"],
         events=[
             E(1938, "built", "The City of Salamanca erected a steel fire tower about 40 feet to its floor in fall 1938 north of the city; it survives, derelict, in Rock City State Forest.", "n202204"),
         ]),
    dict(slug="salmon-lake-mountain", name="Salmon Lake Mountain", tower="us-ny-salmon-lake-mountain", pos="ffla:ny:salmon-lake-mountain:43.9635:-74.6455",
         find=["Salmon Lake"],
         events=[
             E(1933, "built", "The 35-foot Aermotor tower was erected in 1933 on the Whitney Estate; it is on private land.", "n202506"),
         ]),
    dict(slug="snowy-mountain", name="Snowy Mountain Fire Tower", tower="us-ny-snowy-mountain", pos="nhlr:US 1275",
         find=["Snowy", "Snowy Mountain", "Snowy Mt"],
         events=[
             E(1923, "other", "A new observer's cabin was built in 1923.", "n202301"),
             E(2011, "restored", "A restoration led by Forest Ranger Greg George with many partners returned the long-abandoned tower to public use in 2011.", "n201703"),
             E(2024, "modified", "Volunteers attached new safety fencing, hauled up earlier by NYSDEC, to the tower on a July work day.", "n202407", "n202404", "n202405", "projects"),
         ]),
    dict(slug="spruce-mountain", name="Spruce Mountain Fire Tower", tower="us-ny-spruce-mountain", pos="nhlr:US 1182",
         find=["Spruce", "Spruce Mountain", "Spruce Mt"],
         events=[
             E(2015, "restored", "Restoration work on the Spruce Mountain tower and its trail was completed in 2015.", "n202305"),
             E(2023, "closed", "After volunteers noted a structural issue on Sept 21, 2023, the Spruce Mountain tower was closed pending an engineer's inspection.", "n202310"),
         ]),
    dict(slug="st-regis-mountain", name="St. Regis Mountain Fire Tower", tower="us-ny-st-regis-mountain", pos="nhlr:US 117",
         find=["St Regis", "St Regis Mountain", "St. Regis", "St. Regis Mountain", "St. Regis Mt"],
         events=[
             E(1918, "built", "The tower dates from 1918; its centennial was celebrated in 2018.", "n201807", "n201802"),
             E(1925, "other", "A new observer's cabin was built at St. Regis in 1925.", "n202501"),
             E(2015, "restored", "Friends of St. Regis work crews carried out restoration in 2015; as of January 2016 the tower still needed some additional steel before it could be climbed.", "n201601"),
             E(2016, "restored", "Restored by the Friends, NYSDEC and the Student Conservation Association; a new roof was fabricated in June and the tower reopened on 1 September.", "n201606", "n201603", "n201605"),
             E(2019, "restored", "The 24 new cross braces flown in during October 2018 were all fitted; the footings were repaired, the steel under the treated steps primed and the tower painted.", "n201909", "n201908", "n201905"),
             E(2020, "restored", "Volunteers finished priming work on the St. Regis tower over two seasons, including cold-galvanizing drilled holes, and found corrosion in both areas (reported).", "n202011"),
             E(2021, "modified", "Volunteers carried interpretive panels up to the St. Regis tower on Sept 3, 2021 and installed them.", "n202109", "n202011"),
             E(2021, "restored", "Through summer 2021 volunteers repainted the St. Regis tower and made minor repairs to its fencing; full fence replacement remained a priority.", "n202109"),
             E(2022, "restored", "Friends of St. Regis completed their painting project on the tower in spring 2022, hauling paint to the summit.", "n202205", "n202207"),
             E(2023, "modified", "A board member of the Friends of St. Regis mounted a bracket on the tower so a US flag can be flown on steward days.", "n202308"),
             E(2024, "modified", "Two more panoramic view panels, west and north, were mounted in the cab, the third and fourth.", "n202406", "n202409", "n202410"),
             E(2025, "modified", "Friends repaired the old fence on Sept. 10 and installed one short section of new safety fence, with full replacement continuing into 2026.", "n202509"),
         ]),
    dict(slug="sterling", name="Sterling Fire Tower", tower="us-ny-sterling", pos="nhlr:US 102",
         find=["Sterling", "Sterling Forest"],
         events=[
             E(1922, "built", "The 60-foot Aermotor LS 40 tower was built in 1922 and first operated in 1923.", "n201808", "n201807", "n201809"),
             E(2015, "restored", "FFLA, Friends of Sterling Forest and volunteers began restoring the tower with work days from fall 2015, holding seven work dates in all.", "n202201", "n202202"),
             E(2017, "closed", "The tower was reported closed to the public in early 2017, and the FFLA was working to reverse the closure (reported February 2017).", "n201702", "n201703"),
             E(2017, "restored", "About 34 volunteers (Team Rubicon, Friends of Sterling Forest, FFLA, park staff) worked on the tower on 8-9 July; on 12 November volunteers replaced the last landings and steps.", "n201706", "n201702", "n201703", "projects"),
             E(2019, "restored", "New cab windows were made and fitted (fixed ones first, then the operating ones), paid for by ADK North Jersey/Ramapo; a volunteer stained the observer's cabin deck.", "n201910", "n201904", "n201909"),
             E(2022, "assessed", "The engineer's inspection of the closed Sterling Forest tower was completed by August 2022, with the report still awaited.", "n202208"),
             E(2022, "closed", "Sterling Forest tower closed to the public pending an engineer's structural inspection, the same situation as Jackie Jones; still closed in late 2023.", "n202205", "n202206", "n202207"),
         ]),
    dict(slug="stillwater-mountain", name="Stillwater Mountain Fire Tower", tower="us-ny-stillwater-mountain", pos="nhlr:US 904",
         find=["Stillwater"],
         events=[
             E(2016, "modified", "A map table was installed in the cab during the final work weekend of June 5, 2016, shortly before the tower's July 2 reopening.", "n201606", "n201607"),
             E(2016, "restored", "Friends of Stillwater Fire Tower finished restoration begun Sept 2015: windows set, top step built, railing repaired, fencing painted; grand re-opening was July 2, 2016.", "n201606", "n201603", "n201604"),
             E(2018, "restored", "On June 21 volunteers patched cracks in the roof with steel plates and bolted custom brackets on all four sides to hold the roof down.", "n201807"),
         ]),
    dict(slug="swede-mountain", name="Swede Mountain Fire Tower", tower="us-ny-swede-mountain", pos="nhlr:US 1091",
         find=["Swede", "Swede Mountain", "Swede Mt"],
         events=[
             E(1918, "built", "The tower dates from 1918; its centennial was marked in August 2018.", "n201807", "n201802"),
             E(2021, "restored", "The Swede Mountain tower and its new Warren County trail officially reopened to the public at a ribbon cutting on Aug 13, 2021.", "n202108", "n202003"),
             E(2024, "modified", "Warren County, with its Soil and Water Conservation District, added interpretive panels in the tower that identify the visible mountain peaks.", "n202409"),
             E(2024, "restored", "Warren County replaced a missing roof panel on the tower using a $500 FFLA grant; it was installed before the Aug. 31 lighting event.", "n202409", "n202401"),
         ]),
    dict(slug="t-lake-mountain", name="T-Lake Mountain", tower="us-ny-t-lake-mountain", pos="ffla:ny:t-lake-mountain:43.4472:-74.5774",
         find=["T-Lake"],
         events=[
             E(1923, "other", "A new observer's cabin was built in 1923.", "n202301"),
         ]),
    dict(slug="tooley-pond-mountain-at-cathedral-rock", name="Tooley Pond Mountain Lookout (now at Cathedral Rock)", tower="us-ny-tooley-pond-mountain-at-cathedral-rock", pos="nhlr:US 1698",
         find=["Tooley Pond"],
         events=[
             E(1923, "other", "A new observer's cabin was built in 1923.", "n202301"),
         ]),
    dict(slug="tremper-mountain", name="Tremper Mountain Fire Tower", tower="us-ny-tremper-mountain", pos="nhlr:US 224",
         find=["Mount Tremper", "Tremper"],
         events=[
             E(2001, "restored", "The tower reopened on 9 June after refurbishment under the Catskill Fire Tower Project.", "n201709", "n202210"),
             E(2016, "modified", "New panoramas were installed in the cab, arranged with Forest Ranger Marie Ellenbogen, to help visitors identify surrounding mountains (reported July 2016).", "n201607"),
             E(2022, "closed", "The cab of Mount Tremper tower stayed closed for the 2022 season for safety, with its floor and windows needing replacement.", "n202205", "n202206", "n202207"),
             E(2022, "restored", "DEC Operations staff replaced worn steps and landings and broken windows at Mount Tremper tower (June 2022 Catskill bulletin); cab stayed closed.", "n202207"),
         ]),
    dict(slug="utsayantha-mountain", name="Utsayantha Mountain Fire Tower", tower="us-ny-utsayantha-mountain", pos="nhlr:US 1073",
         find=["Mt Utsayantha", "Mt. Utsayantha"],
         events=[
             E(1934, "built", "The CCC built the 59-foot International Derrick tower, the first true fire tower on the summit.", "n202602"),
         ]),
    dict(slug="vandewhacker", name="Vandewhacker Fire Tower", tower="us-ny-vandewhacker", pos="nhlr:US 1281",
         find=["Vanderwhacker", "Vanderwhacker Mountain", "Vanderwhacker Mt", "Vandewhacker"],
         events=[
             E(1911, "built", "The Conservation Commission put up the first, wooden, tower on the summit in 1911.", "n201811"),
             E(1918, "replaced", "The wooden tower was replaced by the current steel tower in 1918.", "n201811"),
             E(2004, "restored", "A local group began restoring the tower in 2000 and it was officially reopened in 2004; the observer's cabin has since fallen into disrepair.", "n201811"),
         ]),
    dict(slug="venetia-at-upper-esopus", name="Upper Esopus Fire Tower", tower="us-ny-venetia-at-upper-esopus", pos="ffla:ny:upper-esopus-relocated-venetia-fl:42.0285:-74.2710",
         find=["Catskill Interpretive", "Esopus", "Upper Esopus", "Venice"],
         events=[
             E(2019, "relocated", "Davana LLC re-erected the Venice, Florida tower at the Catskills visitor center in Mount Tremper (footings in June, steel from 9 July, top lifted by crane); it opened on 3 October.", "n201908", "n201904"),
         ]),
    dict(slug="wakely-mountain", name="Wakely Mountain Fire Tower", tower="us-ny-wakely-mountain", pos="nhlr:US 113",
         find=["Wakely", "Wakely Mountain", "Wakely Mt"],
         events=[
             E(1923, "other", "A new observer's cabin was built in 1923.", "n202301"),
             E(2016, "assessed", "NYSDEC found the tower structurally unsound, the stated basis for closing it to the public; the date of the assessment is not given (reported 2017).", "n201702", "n201703"),
             E(2016, "closed", "NYSDEC closed the tower to the public in fall 2016 as unsafe; the closure was first reported in Feb 2017 and the fall 2016 timing stated in May 2017.", "n201702", "n201703"),
             E(2017, "assessed", "After the tower was found swaying in the wind, Davana LLC evaluated it for NYSDEC and temporarily stabilized the structure.", "n201807"),
             E(2017, "restored", "On May 16, 2017 a NYSDEC crew was flown in and made emergency repairs to stabilize the tower and keep it from toppling; further planned repairs were still pending.", "n201707", "n201705"),
             E(2018, "restored", "Davana LLC crews flown in by helicopter set eight new footings with stainless anchor bolts in June 2018; the tower reopened.", "n201807", "n201805"),
         ]),
    dict(slug="west-bay-at-grafton-lakes-visitor-center", name="West Bay Lookout (from Florida, now at the Grafton Lakes Visitor Center)", tower="us-ny-west-bay-at-grafton-lakes-visitor-center", pos="nhlr:US 1706",
         find=["Grafton Lakes State Park"],
         events=[
             E(2017, "relocated", "Davana LLC erected a fire tower, originally from West Bay, Florida, on Dec 1, 2017 at the state park's new Welcome Center as a model for a nature playspace.", "n201712"),
         ]),
    dict(slug="whiteface-mountain-at-adirondack-experience", name="Whiteface Mountain Lookout (now at the Adirondack Experience)", tower="us-ny-whiteface-mountain-at-adirondack-experience", pos="ffla:ny:adirondack-experience-relocated-whiteface:43.8699:-74.4327",
         find=["Whiteface"],
         events=[
             E(1922, "other", "New observer's cabin built in 1922 under the newly adopted standard 12 by 16 foot cabin plan for observers.", "n202202"),
         ]),
]
